-- The `tasks` table — the Postgres shape of the domain Task (snake_case columns; PostgREST exposes them as-is).
-- This is what the DDD domain would GENERATE for the Supabase adapter (the "App + schema" path). The ownership rule
-- that ScopedTaskRepository enforces ON-DEVICE is here enforced SERVER-SIDE by Row-Level Security:  owner_id = auth.uid().
-- Same rule, the database is now the trusted enforcer — that's the swap.

create table public.tasks (
    id             bigint generated by default as identity primary key,
    title          text        not null,
    description    text,
    category_id    bigint,
    due_date       timestamptz,
    creation_date  timestamptz,
    completed_date timestamptz,
    is_completed   boolean     not null default false,
    is_repeating   boolean     not null default false,
    alarm_interval text,
    owner_id       uuid        not null default auth.uid() references auth.users (id) on delete cascade
);

alter table public.tasks enable row level security;

-- PostgREST checks BOTH a table-level GRANT and the RLS policy: RLS narrows WHICH rows a role may touch, but the role
-- must first hold the table privilege at all. Grant CRUD (and identity-sequence usage) to `authenticated` so signed-in
-- users can reach the policies below; `anon` is intentionally left with no access (the table is owner-private).
grant select, insert, update, delete on public.tasks to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- A user sees and touches ONLY their own rows. (auth.uid() is the signed-in user's id from their JWT.)
create policy "tasks are owner-private (select)" on public.tasks for select using (owner_id = auth.uid());
create policy "tasks are owner-private (insert)" on public.tasks for insert with check (owner_id = auth.uid());
create policy "tasks are owner-private (update)" on public.tasks for update using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "tasks are owner-private (delete)" on public.tasks for delete using (owner_id = auth.uid());
